{
  Foo() {
    break
  }

  Bar() {
    continue
  }
}

// ERROR: [4,3] Not inside a loop
